# Prometheus Pod Monitor (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: controller-manager-metrics-monitor
  namespace: opendatahub
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: training-operator
      app.kubernetes.io/component: controller
  podMetricsEndpoints:
    - port: metrics
